language: node_js
sudo: required

node_js:
- "6.14.4"

services:
  - docker

before_install:
  - docker build -t raks/postmanapi-docker -f Dockerfile .

script:
   - docker run -e CI=true -t raks/postmanapi-docker:latest run /etc/newman/collection2.json
   
deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-postman"
    env: "DockerPostman-env"
    bucket_name: "elasticbeanstalk-us-east-1-375311674115"
    bucket_path: "docker-postman"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
  
