language: node_js
sudo: required

node_js:
- "8.2.1"

services:
  - docker

before_install:
  - docker build -t postman/newman_ubuntu1404 -f Dockerfile .
  
install:
- npm install newman
  
script:
   - docker run -t postman/newman_ubuntu1404 run /tmp/collections/collection2.json 
  
