language: generic
sudo: required

services:
  - docker

before_execution:
  - docker build -t raks/docker-react -f Dockerfile.dev .
  
script:
   - docker run -t postman/newman_ubuntu1404 run /tmp/collections/collection2.json 
  