language: node_js
sudo: required

node_js:
- "6.14.4"

services:
  - docker

before_install:
  - docker build -t raks/postmanapi-docker -f Dockerfile .

install:
- npm install -g newman
 
script:
   - docker run -e CI=true -v $(pwd):/tmp/collections -t raks/postmanapi-docker newman run /tmp/collections/collection2.json 
  
